/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberResponse } from '../../models/member-response';

export interface Member$Params {
  id: string;
}

export function member(http: HttpClient, rootUrl: string, params: Member$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberResponse>> {
  const rb = new RequestBuilder(rootUrl, member.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberResponse>;
    })
  );
}

member.PATH = '/members/{id}';
