/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Get$Params as Get$Params } from './fn/books/get';
export { get as get } from './fn/books/get';
export type { Update$Params as Update$Params } from './fn/books/update';
export { update as update } from './fn/books/update';
export type { Browse$Params as Browse$Params } from './fn/books/browse';
export { browse as browse } from './fn/books/browse';
export type { Create$Params as Create$Params } from './fn/books/create';
export { create as create } from './fn/books/create';
export type { Cover$Params as Cover$Params } from './fn/books/cover';
export { cover as cover } from './fn/books/cover';
export type { UploadCover$Params as UploadCover$Params } from './fn/books/upload-cover';
export { uploadCover as uploadCover } from './fn/books/upload-cover';
export type { ToggleShareable$Params as ToggleShareable$Params } from './fn/books/toggle-shareable';
export { toggleShareable as toggleShareable } from './fn/books/toggle-shareable';
export type { ToggleArchived$Params as ToggleArchived$Params } from './fn/books/toggle-archived';
export { toggleArchived as toggleArchived } from './fn/books/toggle-archived';
export type { Mine$Params as Mine$Params } from './fn/books/mine';
export { mine as mine } from './fn/books/mine';
export type { Give$Params as Give$Params } from './fn/feedback/give';
export { give as give } from './fn/feedback/give';
export type { ForBook$Params as ForBook$Params } from './fn/feedback/for-book';
export { forBook as forBook } from './fn/feedback/for-book';
export type { GiveBack$Params as GiveBack$Params } from './fn/lending/give-back';
export { giveBack as giveBack } from './fn/lending/give-back';
export type { ApproveReturn$Params as ApproveReturn$Params } from './fn/lending/approve-return';
export { approveReturn as approveReturn } from './fn/lending/approve-return';
export type { Borrow$Params as Borrow$Params } from './fn/lending/borrow';
export { borrow as borrow } from './fn/lending/borrow';
export type { ReturnedToMe$Params as ReturnedToMe$Params } from './fn/lending/returned-to-me';
export { returnedToMe as returnedToMe } from './fn/lending/returned-to-me';
export type { Borrowed$Params as Borrowed$Params } from './fn/lending/borrowed';
export { borrowed as borrowed } from './fn/lending/borrowed';
export type { Me$Params as Me$Params } from './fn/profile/me';
export { me as me } from './fn/profile/me';
