/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  archived?: boolean;
  authorName?: string;
  borrowed?: boolean;
  hasCover?: boolean;
  id?: number;
  isbn?: string;
  mine?: boolean;
  ownerName?: string;
  rating?: number;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
