/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackResponse {
  authorName?: string;
  comment?: string;
  createdAt?: string;
  id?: number;
  mine?: boolean;
  rating?: number;
}
