/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoanResponse {
  approved?: boolean;
  authorName?: string;
  bookId?: number;
  borrowedAt?: string;
  dueAt?: string;
  hasCover?: boolean;
  id?: number;
  isbn?: string;
  overdue?: boolean;
  returned?: boolean;
  returnedAt?: string;
  title?: string;
}
