/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanResponse } from '../models/loan-response';
export interface PageResponseLoanResponse {
  content?: Array<LoanResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
