/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationResponse {
  authorName?: string;
  bookId?: number;
  createdAt?: string;
  id?: number;
  position?: number;
  title?: string;
}
